### ISSUE TITLE
pip install compiler error with fastlz

### ISSUE THREAD

**Issue by scrowe** [jaredsuttles/python-fastlz#1]
I'm having a compiling issue for the fastlz module and was hoping you could help me understand or fix it.   I've tried compiling with the default compiler as well as mingw, but they both prompt the same error.

Here's my log, resulting from calling pip install fastlz:

> C:\Python27\Scripts>pip install fastlz
> Collecting fastlz
>   Using cached fastlz-0.0.1.tar.gz
> Installing collected packages: fastlz
>   Running setup.py install for fastlz ... error
>     Complete output from command c:\python27\python.exe -u -c "import setuptools
> , tokenize;**file**='c:\users\user1\appdata\local\temp\pip-build-bnrzll\
> fastlz\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().
> replace('\r\n', '\n'), **file**, 'exec'))" install --record c:\users\user1\appd
> ata\local\temp\pip-olbxjw-record\install-record.txt --single-version-externally-
> managed --compile:
>     running install
>     running build
>     running build_ext
>     building 'fastlz' extension
>     creating build
>     creating build\temp.win32-2.7
>     creating build\temp.win32-2.7\Release
>     creating build\temp.win32-2.7\Release\fastlz
>     C:\Users\user1\AppData\Local\Programs\Common\Microsoft\Visual C++ for Pytho
> n\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ifastlz -Ic:\python27\
> include -Ic:\python27\PC /Tcfastlz.c /Fobuild\temp.win32-2.7\Release\fastlz.obj
>     fastlz.c
>     fastlz.c(33) : error C2065: 'uint32_t' : undeclared identifier
>     fastlz.c(33) : error C2065: 'uint32_t' : undeclared identifier
>     fastlz.c(33) : error C2064: term does not evaluate to a function taking 302
> arguments
>     fastlz.c(37) : error C2065: 'uint32_t' : undeclared identifier
>     fastlz.c(40) : error C2065: 'uint32_t' : undeclared identifier
>     fastlz.c(50) : error C2065: 'uint32_t' : undeclared identifier
>     fastlz.c(64) : error C2065: 'uint32_t' : undeclared identifier
>     fastlz.c(64) : error C2146: syntax error : missing ';' before identifier 'ou
> tput_len'
>     fastlz.c(64) : error C2065: 'output_len' : undeclared identifier
>     fastlz.c(64) : error C2065: 'decompressed_len' : undeclared identifier
>     fastlz.c(69) : error C2065: 'uint32_t' : undeclared identifier
>     fastlz.c(69) : error C2146: syntax error : missing ')' before identifier 'in
> put_len'
>     fastlz.c(69) : error C2065: 'uint32_t' : undeclared identifier
>     fastlz.c(69) : error C2059: syntax error : ')'
>     fastlz.c(69) : error C2143: syntax error : missing ';' before '{'
>     fastlz.c(69) : warning C4552: '<' : operator has no effect; expected operato
> r with side-effect
>     fastlz.c(74) : error C2065: 'output_len' : undeclared identifier
>     fastlz.c(74) : error C2065: 'uint32_t' : undeclared identifier
>     fastlz.c(76) : error C2065: 'output_len' : undeclared identifier
>     fastlz.c(81) : error C2065: 'output_len' : undeclared identifier
>     fastlz.c(85) : error C2065: 'uint32_t' : undeclared identifier
>     fastlz.c(86) : error C2065: 'uint32_t' : undeclared identifier
>     fastlz.c(88) : error C2065: 'decompressed_len' : undeclared identifier
>     fastlz.c(88) : error C2065: 'uint32_t' : undeclared identifier
>     fastlz.c(88) : error C2146: syntax error : missing ';' before identifier 'fa
> stlz_decompress'
>     fastlz.c(89) : error C2065: 'output_len' : undeclared identifier
>     fastlz.c(91) : error C2065: 'decompressed_len' : undeclared identifier
>     fastlz.c(91) : error C2065: 'output_len' : undeclared identifier
>     fastlz.c(100) : error C2065: 'output_len' : undeclared identifier
>     error: command 'C:\Users\user1\AppData\Local\Programs\Common\Microso
> ft\Visual C++ for Python\9.0\VC\Bin\cl.exe' failed with exit status 2
> 
> ```
> ----------------------------------------
> ```
> 
> Command "c:\python27\python.exe -u -c "import setuptools, tokenize;**file**='c:\
> \users\user1\appdata\local\temp\pip-build-bnrzll\fastlz\setup.py';exec(c
> ompile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), _
> _file__, 'exec'))" install --record c:\users\user1\appdata\local\temp\pip-olbxj
> w-record\install-record.txt --single-version-externally-managed --compile" faile
> d with error code 1 in c:\users\user1\appdata\local\temp\pip-build-bnrzll\fastl
> z\

Do you have any idea what could be causing this compiler issue?

**Comment by jaredsuttles** [comment]
@scrowe Thanks for the feedback.

If you clone the repo and add `#include "stdint.h"` to the top of `fastlz.c`, see if that fixes your problem.

You can just test it out by using `python setup.py build_ext --inplace`

**Comment by scrowe** [comment]
Haha, thanks for the swift reply.  I actually fixed it almost directly after I made that post by typedef-ing unsigned __int32 uint32_t; as a duct tape solution.  Yours is, obviously, much better.

Thanks again!

**Comment by scrowe** [comment]
Just out of curiosity though, are you going to push the updated code to pip?  Windows users will love you, and so will I when I need to utilize this module again after I've long forgotten this fix.
